### PR TITLE
Added ability to output to different streams

### LINKED ISSUE #2: Support any class which looks like an std::basic_ostream?
It's right now std::cout everywhere. It would be cool that if we could use own classes (e.g. Qt loggers / Boost.log loggers / any another with operator << )

### PR DESCRIPTION
**Pull request by AlexanderDavid**
Added a new parameter to the constructor to change the output stream. This works with the normal cout/cerr streams as well as file streams. I wanted to add another function that modified the stream rather than setting it in the constructor but C++ has deleted the copy constructor for streams so it won't work:

https://stackoverflow.com/questions/6010864/why-copying-stringstream-is-not-allowed/6010930#6010930

I'd appreciate you labeling this PR as `hacktoberfest-accepted` and maybe considering marking this repo for participation in [Hacktoberfest](https://hacktoberfest.com/)!

### CODE REVIEW

**Comment by gipert** [comment]
If copy isn't allowed, why don't you just swap the internal reference with the setter you had in mind?

**Comment by AlexanderDavid** [comment]
I don't think I understand. I the copy constructor for ostream is deleted so you can only assign on initialization AFAIK. If, when the object is constructed, the ostream is pointing at cerr then it won't be able to be reassigned.

**Comment by AlexanderDavid** [comment]
Alright I think I got what you meant. There's now an option to set in the constructor and after initialization.

**Comment by gipert** [comment]
Thanks!

**Pull request merged**
